# frontend/docker-compose.preprod.yml
services:

### Application ###

  frontend:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3032:80"
    restart: always
    networks:
      - licensync_network
      - nginx_proxy_manager_npm_network
    pull_policy: build

### Networks ###

networks:
  licensync_network:
    driver: bridge
  nginx_proxy_manager_npm_network:
    name: nginx_proxy_manager_npm_network
    external: true
