services:
  ### Application ###

  fix-permissions:
    image: alpine:latest
    command:
      [
        "sh",
        "-c",
        "mkdir -p /var/opt/mssql/.system && chown -R 10001:0 /var/opt/mssql && chmod -R 770 /var/opt/mssql",
      ]
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - licensync_network
    deploy:
      mode: replicated
      replicas: 1
    restart: "no"

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "10001:0"
    env_file:
      - ../../.env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "5014:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - licensync_network
    depends_on:
      fix-permissions:
        condition: service_completed_successfully

  backend:
    build:
      context: .
      dockerfile: ./API/docker/dev/Dockerfile
      args:
        ENV: development
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    volumes:
      - ./API:/src/backend
      - file_data:/src/backend/Uploads
    depends_on:
      - database
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - licensync_network

### Volumes ###

volumes:
  mssql_data:
  file_data:

### Networks ###

networks:
  licensync_network:
    driver: bridge
