# backend-microservices/backend/docker-compose.preprod.yml

services:

### Application ###

  fix-permissions:
    image: alpine:latest
    command:
      [
        "sh",
        "-c",
        "mkdir -p /var/opt/mssql/.system && chown -R 10001:0 /var/opt/mssql && chmod -R 770 /var/opt/mssql",
      ]
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - licensync_network
    deploy:
      mode: replicated
      replicas: 1
    restart: "no"

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "10001:0"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${PASSWORD}"
    ports:
      - "3030:1433"
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - licensync_network

  backend:
    build:
      context: .
      dockerfile: ./API/docker/prod/Dockerfile
    ports:
      - "3031:8080"
    restart: always
    volumes:
      - file_data:/src/backend/Uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
    networks:
      - licensync_network
      - nginx_proxy_manager_npm_network
    pull_policy: build

### Volumes ###

volumes:
  mssql_data:
  file_data:

### Networks ###

networks:
  licensync_network:
    driver: bridge
  nginx_proxy_manager_npm_network:
    external:
      name: nginx_proxy_manager_npm_network
